[package]
name = "paris"
version = "1.2.2"
authors = ["Poly <alexhexan22@gmail.com>"]
edition = "2018"

documentation = "https://docs.rs/paris"
homepage = "https://github.com/0x20F/logger"
repository = "https://github.com/0x20F/logger"
readme = "README.md"

keywords = ["log", "logger", "simple", "terminal", "cli"]
categories = ["command-line-interface", "command-line-utilities"]

description = "A simple logger for your CLI apps or other things you want in the terminal"

license = "GPL-3.0-or-later"

exclude = [
    "example/*",
    "tests/*",
    ".github/*"
]



[badges]
maintenance = { status = "actively-developed" }



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"



[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "formatting"
harness = false