[package]
name = "paris"
version = "1.0.0"
authors = ["Poly <alexhexan22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
chrono = "0.4.10"