[package]
name = "paris"
version = "1.0.1"
authors = ["Poly <alexhexan22@gmail.com>"]
edition = "2018"

documentation = "https://github.com/SirTheViking/logger"
homepage = "https://github.com/SirTheViking/logger"
repository = "https://github.com/SirTheViking/logger"

keywords = ["log", "logging", "logger", "simple", "terminal", "cli"]
categories = ["command-line-interface", "command-line-utilities"]

description = "A simple logger for your CLI apps or other things you want in the terminal"

license = "GPL-3.0-or-later"
maintenance = { status = "passively-maintained" }

exclude = [
    "tests/*",
    ".github/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
chrono = "0.4.10"
