[package]
name = "paris"
version = "1.1.0"
authors = ["Poly <alexhexan22@gmail.com>"]
edition = "2018"

documentation = "https://docs.rs/paris"
homepage = "https://github.com/SirTheViking/logger"
repository = "https://github.com/SirTheViking/logger"
readme = "README.md"

keywords = ["log", "logger", "simple", "terminal", "cli"]
categories = ["command-line-interface", "command-line-utilities"]

description = "A simple logger for your CLI apps or other things you want in the terminal"

license = "GPL-3.0-or-later"

exclude = [
    "tests/*",
    ".github/*"
]



[badges]
maintenance = { status = "actively-developed" }



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
chrono = "0.4.10"
regex = "1"
lazy_static = "1"
